nodeLinker: node-modules

packageExtensions:
  "@opentelemetry/resources@*":
    dependencies:
      "@opentelemetry/resources": "1.25.1"
  "@opentelemetry/sdk-metrics@*":
    dependencies:
      "@opentelemetry/sdk-metrics": "1.25.1"
  "@opentelemetry/sdk-trace-base@*":
    dependencies:
      "@opentelemetry/sdk-trace-base": "1.25.1"
  "@opentelemetry/semantic-conventions@*":
    dependencies:
      "@opentelemetry/semantic-conventions": "1.25.1"
  "@azure/functions@*":
    dependencies:
      "@azure/functions": "4.5.0"
