# Docs for the Azure Functions action: https://github.com/Azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Function - tracing-test

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      # This is required for requesting the JWT
      id-token: write

    environment:
      name: "Production"
      url: ${{ steps.deploy-to-functionapp.outputs.app-url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"

      - name: yarn install, build, and test
        run: |
          yarn install
          yarn build

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FBCE06B54D6E43E899AD3ABABE41C48A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3F6609A225434E128CD34E54BA7EF19E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6A6DC146C514481785C39D6B3F06E1D4 }}

      - name: "Deploy to Azure Function App"
        id: deploy-to-functionapp
        uses: Azure/functions-action@v1
        with:
          app-name: "tracing-test"
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
